name: coast_audio_miniaudio
description: An extension package for coast_audio using miniaudio.
version: 0.0.4
repository: https://github.com/SKKbySSK/coast_audio/tree/main/packages/coast_audio_miniaudio

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ffi: ^2.1.0
  coast_audio: ^0.0.4

dev_dependencies:
  ffigen: ^9.0.1
  lints: ^2.0.0
  test: ^1.16.0

ffigen:
  name: "MaBridge"
  output: "lib/generated/ma_bridge_bindings.dart"
  headers:
    entry-points:
      - "mabridge/src/**.h"
  functions:
    leaf:
      exclude:
        - "mab_audio_encoder_init"
        - "mab_audio_encoder_encode"
        - "mab_audio_encoder_uninit"
        - "mab_audio_decoder_init"
        - "mab_audio_decoder_decode"
        - "mab_audio_decoder_get_cursor"
        - "mab_audio_decoder_set_cursor"
        - "mab_audio_decoder_get_length"
        - "mab_audio_decoder_uninit"
        - "mab_device_init"
