name: coast_audio_fft
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/SKKbySSK/coast_audio/tree/main/packages/coast_audio_fft

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fftea: ^1.2.0+1
  coast_audio: ^0.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
